### ISSUE TITLE
Post Big Bang Skill

### ISSUE THREAD

**Issue by mlhnp** [MorningLit/maple-wordle-public#10]
The skill used in today's (2024/05/27) skill mode did not exist pre big bang.
<details>
  <summary>Skill</summary>

  ![alt text](https://www.maplewordle.com/images/skills/Vengeance.png "Vengeance") Vengeance for Bowmaster
</details>

See:
[v92](https://maplestory.io/api/GMS/92/job/312/skillbook)
[v93 (Big Bang)](https://maplestory.io/api/GMS/93/job/312/skillbook)

**Comment by MorningLit** [comment]
Oh looks like you are right 😓, I have removed the skill, nice find!
